run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  depguard:
    rules:
      main:
        files:
          - "$all"
          - "!$test"
        list-mode: lax
        allow:
          - $gostd
          - github.com/satococoa/git-wtp
          - github.com/urfave/cli/v3
          - go.yaml.in/yaml/v3
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/satococoa/git-wtp
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint

linters:
  enable:
    - bodyclose
    - copyloopvar     # replaces exportloopref for Go 1.22+
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd             # replaces gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused          # replaces deadcode, structcheck, varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - gosec
    - linters:
        - lll
      source: "^//go:generate "

  max-issues-per-linter: 0
  max-same-issues: 0