version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    depguard:
      rules:
        main:
          files:
            - "$all"
            - "!$test"
          list-mode: lax
          allow:
            - $gostd
            - github.com/satococoa/wtp/v2
            - github.com/urfave/cli/v3
            - go.yaml.in/yaml/v3
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    lll:
      line-length: 120
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
    revive:
      rules:
        - name: indent-error-flow
        - name: exported
        - name: package-comments
        - name: unused-parameter
        - name: unused-receiver

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - mnd
          - goconst
          - gosec
      - linters:
          - lll
        source: "^//go:generate "

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      # Task-based formatting sets GOIMPORTS_LOCAL_PREFIXES via `go list -m`.
      # The default keeps CI and ad-hoc runs deterministic if the task runner
      # is bypassed.
      local-prefixes:
        - ${GOIMPORTS_LOCAL_PREFIXES:-github.com/satococoa/wtp/v2}

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
