version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: wtp
    binary: wtp
    main: ./cmd/wtp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64  # Intel Macを除外
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: wtp
    format: tar.gz
    name_template: >-
      wtp_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CONTRIBUTING.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

brews:
  - name: wtp
    repository:
      owner: satococoa
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/satococoa/wtp/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/satococoa/wtp"
    description: "Worktree Plus - Enhanced worktree management with automated setup and hooks"
    license: "MIT"
    skip_upload: auto
    dependencies:
      - name: git
    install: |
      bin.install "wtp"

      (bash_completion/"wtp").write <<~'EOS'
        _wtp_lazy_init() {
          local script
          script="$(command wtp shell-init bash 2>/dev/null)"
          if [[ $? -ne 0 || -z "$script" ]]; then
            return 1
          fi

          eval "$script"

          if declare -f __wtp_bash_autocomplete >/dev/null 2>&1; then
            __wtp_bash_autocomplete "$@"
          fi
        }

        complete -o bashdefault -o default -o nospace -F _wtp_lazy_init wtp
      EOS

      (zsh_completion/"_wtp").write <<~'EOS'
        #compdef wtp

        _wtp_lazy_init() {
          local original_def
          original_def="${functions[_wtp]-}"

          local script
          script="$(command wtp shell-init zsh 2>/dev/null)"
          if [[ $? -ne 0 || -z "$script" ]]; then
            return 1
          fi

          eval "$script"

          local updated_def
          updated_def="${functions[_wtp]-}"

          if whence -w _wtp >/dev/null 2>&1 && [[ "$updated_def" != "$original_def" ]]; then
            _wtp "$@"
          fi
        }

        _wtp() {
          _wtp_lazy_init "$@"
        }

        compdef _wtp_lazy_init wtp
      EOS

      (fish_completion/"wtp.fish").write <<~'EOS'
        if command -sq wtp
          command wtp shell-init fish | source
        end
      EOS
    test: |
      system "#{bin}/wtp", "--help"

release:
  github:
    owner: satococoa
    name: wtp
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## Worktree Plus (wtp) {{.Version}}

    Welcome to this new release!

  footer: |
    ## Installation

    ### Homebrew
    ```bash
    brew install satococoa/tap/wtp
    ```

    ### Manual Installation
    Download the appropriate binary for your platform from the assets below.

    **Full Changelog**: https://github.com/satococoa/wtp/compare/{{.PreviousTag}}...{{.Tag}}

nfpms:
  - id: wtp
    package_name: wtp
    file_name_template: >-
      wtp_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    vendor: satococoa
    homepage: https://github.com/satococoa/wtp
    maintainer: satococoa <satococoa@example.com>
    description: |-
      Worktree Plus - Enhanced worktree management with automated setup and hooks.
      A powerful Git worktree management tool that extends git's worktree functionality
      with automated setup, branch tracking, and project-specific hooks.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - git
    bindir: /usr/bin
