version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - mkdir -p dist/completions
    - go run ./cmd/wtp completion bash > dist/completions/wtp.bash
    - go run ./cmd/wtp completion zsh > dist/completions/wtp.zsh
    - go run ./cmd/wtp completion fish > dist/completions/wtp.fish

builds:
  - id: wtp
    binary: wtp
    main: ./cmd/wtp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: wtp
    format: tar.gz
    name_template: >-
      wtp_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CONTRIBUTING.md
      - dist/completions/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

brews:
  - name: wtp
    repository:
      owner: satococoa
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/satococoa/wtp/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/satococoa/wtp"
    description: "Worktree Plus - Enhanced worktree management with automated setup and hooks"
    license: "MIT"
    skip_upload: auto
    dependencies:
      - name: git
    install: |
      bin.install "wtp"
      bash_completion.install "dist/completions/wtp.bash" => "wtp"
      zsh_completion.install "dist/completions/wtp.zsh" => "_wtp"
      fish_completion.install "dist/completions/wtp.fish"
    test: |
      system "#{bin}/wtp", "--help"

release:
  github:
    owner: satococoa
    name: wtp
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## Worktree Plus (wtp) {{.Version}}

    Welcome to this new release!

  footer: |
    ## Installation

    ### Homebrew
    ```bash
    brew install satococoa/tap/wtp
    ```

    ### Manual Installation
    Download the appropriate binary for your platform from the assets below.

    **Full Changelog**: https://github.com/satococoa/wtp/compare/{{.PreviousTag}}...{{.Tag}}

nfpms:
  - id: wtp
    package_name: wtp
    file_name_template: >-
      wtp_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    vendor: satococoa
    homepage: https://github.com/satococoa/wtp
    maintainer: satococoa <satococoa@example.com>
    description: |-
      Worktree Plus - Enhanced worktree management with automated setup and hooks.
      A powerful Git worktree management tool that extends git's worktree functionality
      with automated setup, branch tracking, and project-specific hooks.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - git
    bindir: /usr/bin
    contents:
      - src: "dist/completions/wtp.bash"
        dst: "/usr/share/bash-completion/completions/wtp"
        file_info:
          mode: 0644
      - src: "dist/completions/wtp.zsh"
        dst: "/usr/share/zsh/site-functions/_wtp"
        file_info:
          mode: 0644
      - src: "dist/completions/wtp.fish"
        dst: "/usr/share/fish/vendor_completions.d/wtp.fish"
        file_info:
          mode: 0644