version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: wtp
    binary: wtp
    main: ./cmd/wtp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64  # Intel Macを除外
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: wtp
    format: tar.gz
    name_template: >-
      wtp_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CONTRIBUTING.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

brews:
  - name: wtp
    repository:
      owner: satococoa
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/satococoa/wtp/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/satococoa/wtp"
    description: "Worktree Plus - Enhanced worktree management with automated setup and hooks"
    license: "MIT"
    skip_upload: auto
    dependencies:
      - name: git
    install: |
      bin.install "wtp"

      (bash_completion/"wtp").write <<~'EOS'
        # wtp lazy shell-init for bash (installed via Homebrew)
        _wtp_lazy_init() {
          if [[ -z "${WTP_SHELL_INIT_DONE:-}" ]]; then
            local __wtp_init __wtp_status
            __wtp_init="$(command wtp shell-init bash 2>/dev/null)"
            __wtp_status=$?
            if [[ $__wtp_status -ne 0 || -z "$__wtp_init" ]]; then
              __wtp_init="$(command wtp completion bash 2>/dev/null)"
              __wtp_status=$?
            fi
            if [[ $__wtp_status -ne 0 || -z "$__wtp_init" ]]; then
              return 124
            fi

            eval "$__wtp_init"
            export WTP_SHELL_INIT_DONE=1
          fi

          if declare -F __wtp_bash_autocomplete >/dev/null 2>&1; then
            __wtp_bash_autocomplete "$@"
          elif declare -F _wtp >/dev/null 2>&1; then
            _wtp "$@"
          fi
        }

        complete -o bashdefault -o default -o nospace -F _wtp_lazy_init wtp
      EOS

      (zsh_completion/"_wtp").write <<~'EOS'
        #compdef wtp

        _wtp_lazy_init() {
          if [[ -z ${WTP_SHELL_INIT_DONE-} ]]; then
            local __wtp_init __wtp_status
            __wtp_init="$(command wtp shell-init zsh 2>/dev/null)"
            __wtp_status=$?
            if [[ $__wtp_status -ne 0 || -z "$__wtp_init" ]]; then
              __wtp_init="$(command wtp completion zsh 2>/dev/null)"
              __wtp_status=$?
            fi
            if [[ $__wtp_status -ne 0 || -z "$__wtp_init" ]]; then
              return 1
            fi

            eval "$__wtp_init"
            export WTP_SHELL_INIT_DONE=1
          fi

          if typeset -f _wtp >/dev/null 2>&1; then
            _wtp "$@"
          fi
        }

        compdef _wtp_lazy_init wtp
      EOS

      (fish_completion/"wtp.fish").write <<~'EOS'
        function __wtp_lazy_setup --on-event fish_prompt --description 'Lazy shell-init for wtp (Homebrew)'
            functions -e __wtp_lazy_setup

            if not set -q WTP_SHELL_INIT_DONE
                command wtp shell-init fish ^/dev/null | source
                set -l __wtp_status $status
                if test $__wtp_status -ne 0
                    command wtp completion fish ^/dev/null | source
                    set __wtp_status $status
                end
                if test $__wtp_status -ne 0
                    return
                end

                set -gx WTP_SHELL_INIT_DONE 1
            end
        end
      EOS
    test: |
      system "#{bin}/wtp", "--help"

release:
  github:
    owner: satococoa
    name: wtp
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## Worktree Plus (wtp) {{.Version}}

    Welcome to this new release!

  footer: |
    ## Installation

    ### Homebrew
    ```bash
    brew install satococoa/tap/wtp
    ```

    ### Manual Installation
    Download the appropriate binary for your platform from the assets below.

    **Full Changelog**: https://github.com/satococoa/wtp/compare/{{.PreviousTag}}...{{.Tag}}

nfpms:
  - id: wtp
    package_name: wtp
    file_name_template: >-
      wtp_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    vendor: satococoa
    homepage: https://github.com/satococoa/wtp
    maintainer: satococoa <satococoa@example.com>
    description: |-
      Worktree Plus - Enhanced worktree management with automated setup and hooks.
      A powerful Git worktree management tool that extends git's worktree functionality
      with automated setup, branch tracking, and project-specific hooks.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - git
    bindir: /usr/bin
