#!/bin/bash

# This is a shell completion script auto-generated by https://github.com/urfave/cli for bash.

# Macs have bash3 for which the bash-completion package doesn't include
# _init_completion. This is a minimal version of that function.
__wtp_init_completion() {
  COMPREPLY=()
  _get_comp_words_by_ref "$@" cur prev words cword
}


_wtp_sanitize_completion_list() {
	local line suffix result=()
	while IFS= read -r line; do
		if [[ "$line" == *:* ]]; then
			suffix=${line#*:}
			if [[ "$suffix" == *" "* ]]; then
				result+=("${line%%:*}")
				continue
			fi
		fi
		result+=("$line")
	done
	printf "%s\n" "${result[@]}"
}

__wtp_bash_autocomplete() {
  if [[ "${COMP_WORDS[0]}" != "source" ]]; then
    local cur opts base words
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    if declare -F _init_completion >/dev/null 2>&1; then
      _init_completion -n "=:" || return
    else
      __wtp_init_completion -n "=:" || return
    fi
    words=("${words[@]:0:$cword}")
    if [[ "$cur" == "-"* ]]; then
      requestComp="${words[*]} ${cur} --generate-shell-completion"
    else
      requestComp="${words[*]} --generate-shell-completion"
    fi
    opts=$(eval "${requestComp}" 2>/dev/null)
    opts=$(_wtp_sanitize_completion_list <<<"${opts}")
    COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
    return 0
  fi
}

complete -o bashdefault -o default -o nospace -F __wtp_bash_autocomplete wtp

